### ISSUE TITLE
Fix "This contact hasn’t published the dm3 profile yet." for existing conversation

### ISSUE THREAD

**Issue by malteish** [dm3-org/dm3#1033]
How to provoke this error:
1. open testing app in browser A, connect with address A
2. open testing app in browser B, connect with address B
3. as A, create conversation with B and send a message
4. conversation pops up in browser B, with message, but also with this hint: `This contact hasn’t published the dm3 profile yet.
You can already write messages. But these will not be sent until the recipient has published the dm3 profile. Until then they are saved in your storage.` (see screenshot)
5. A can send messages to B and they are delivered, but B's messages to A are never delivered. 
6. to make things worse, A doesn't get another error indicating this

![image](https://github.com/dm3-org/dm3/assets/102788938/b6cbea04-a2fd-4bac-9142-95a10a092093)

**Comment by AlexNi245** [comment]
addressed in #1069
