### ISSUE TITLE
Fix or remove the double checkmark

### ISSUE THREAD

**Issue by malteish** [dm3-org/dm3#1034]
Our messages sometimes have double checkmarks. 
![image](https://github.com/dm3-org/dm3/assets/102788938/c62a5c2c-b5f7-45aa-a78f-483bd982e7ab)

And sometimes single checkmarks.
![image](https://github.com/dm3-org/dm3/assets/102788938/4ca6b08b-d81a-4e26-8f9f-670fb0ccc52d)

What does this mean? I have seen double checkmarks on messages that were not delivered. They must have a meaning or must be removed.

**Comment by AlexNi245** [comment]
fixed by #1066
