### ISSUE TITLE
BUG: ENS Avatar is not shown correctly

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#1084]
## Current behavior
The NFT Avatar at ENS name is not rendered, but missing picture information is shown (see pic 01 - rouven.eth). Also, if a link is included, it is not shown (see pic 01 - stkux.eth)

## Requirement
Avatar pictures (also NFT images) need to be rendered correctly. If the image is not renderable (for whatever reason), the pixy must be shown, but no missing picture info. (test it with rouven.eth and stkux.eth at mainnet)

## Pitcures
01
<img width="405" alt="image" src="https://github.com/dm3-org/dm3/assets/26625404/d918addf-eb74-4fbb-a54f-aee300f26b8b">

**Comment by AlexNi245** [comment]
fixed by #1086
