### ISSUE TITLE
DS1 - Create own package for the DeliveryService

### ISSUE THREAD

**Issue by AlexNi245** [dm3-org/dm3#778]
At the moment the DeliveryService is part of the overall dm3-backend workspace. It should become an independent package as it is supposed to be operated without the other backend components

- [x] Create a new workspace dm3-delivery-service
- [x] Move the express app that is currently located in delivery.ts into that workspace
- [x] rpc-proxy.ts contains a method called DM3_SUBMIT_MESSAGE move this method to the new workspace aswell
- [x] Integrate the new workspace to the build pipeline

**Comment by malteish** [comment]
Todo: 
- extract auth for both backend and ds to use
