### ISSUE TITLE
DS2 - Refine DeliveryService Authentication

### ISSUE THREAD

**Issue by AlexNi245** [dm3-org/dm3#779]
At the moment the method behind /delivery is gated via Token Auth. That however would prevent anyone who is not registered on that deliverysService from sending messages to a recipient.

As defined in the specification a delivery has to accept all incoming messages for certain users regardless of the origin

- [x] Remove auth for methods that are used to receive messages. Endpoints for getMessage and syncAck should remain permissioned
- [ ] You might eventually protect with endpoint with the DM3-SpamProtection. However keep in mind that at the moment only nonce, EthValue, or a tokenValue can be for the SpamProtection. That would render a lot of off-chain messages as spam

**Comment by malteish** [comment]
removed auth requirement for message submission here:
- https://github.com/dm3-org/dm3/pull/899/commits/739ee0b846dd737b60b4b7c17d1791bbe409fb83
- https://github.com/dm3-org/dm3/pull/899/commits/6e184137fddd81a51321503cd0bea99f735faadf

... and completed with several other commits

**Comment by malteish** [comment]
done, without spam protection though.
