### ISSUE TITLE
dm3-react:  Failed to resolve entry for package "dm3-react". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by wighawag** [dm3-org/dm3#786]
Hi,

I am trying to use dm3-react in a vite project but it fails with 

```
dm3-react:  Failed to resolve entry for package "dm3-react". The package may have incorrect main/module/exports specified in its package.json.
```

I suppose your package.json do not follow the correct convention and vite will not proceed

Reproduction: https://github.com/bug-reproduction/vite-dm3-react

```
git clone https://github.com/bug-reproduction/vite-dm3-react
cd vite-dm3-react
pnpm i
pnpm dev
```

**Comment by steffenkux** [comment]
@wighawag i looked into the demo project. I uses the dm3-react package, which is the old implementation (beta2). The new package at NPM is @dm3-org/dm3-messenger-widget.

An guide how to include it into an react app is here: https://gist.github.com/steffenkux/c93e65a9a5899d965bdadb3feb56e7a1

**Comment by wighawag** [comment]
thanks for looking @steffenkux 
Yes I realised I was using thr wrong package afterward, the new issue is this : https://github.com/dm3-org/dm3/issues/788

Closing this then
