### ISSUE TITLE
Optimism Dm3 names

### ISSUE THREAD

**Issue by AlexNi245** [dm3-org/dm3#813]
A Dm3 user should be able to register themselves an Optimism domain name. This name is stored on the Optimism Chain within a Smart Contract and is resolved using the ENS-Bedrock Resolver.

### Messenger Widget
A user should be able to use the Configure Profile dialog to register an Optimism Domain name.
- [ ] Add a new row for Dm3 on-chain names
- [ ] Add a dropdown field to choose the selected network (in this iteration only Optimism is supported, but in the future, there might be more networks to come)
- [ ] Add a function "publishOptimismName" similar to publishGenomeName to interact with the Smart Contract on Optimism
- [ ] Add Op TLDREsolver to useTldResolver hook

### Smart Contract
Optimism name should be stored on-chain using a dedicated Smart Contract
- [x] Add a function to claim a domain name. One address can only claim one name (add event as well)
- [x] Add a function to get the address for a given name 
- [x] Add a function to get the domain name for a given address (reverse record)
- [x] TBD Do we want an admin functionality

### Infrastructure
The Optimism Gateway has to be hosted somewhere
- [x] Contact Gateway to see if they can help with it

### Resources

Figma: (see config fir dm3 name)
https://www.figma.com/file/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?type=design&node-id=85-2774&mode=design
Description:
* a dropdown box to select "Cloud service by dm3" or "Optimism" (in future more)
* according to the selected type, the name is ... .user.dm3.eth or ... .op.dm3.eth (changes if the dropdown is changed)

**Comment by steffenkux** [comment]
Additional requirement: only one name per address mintable
