### ISSUE TITLE
UI-Tests (01-05)

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#923]
### TESTED VERSION: STAGING 2024-05-08T10:20:55 a0ddf4

> **PRIO1** ... critical bug, blocks release
> **PRIO2** ... bug, but doesn't block release
> **PRIO3** ... not nice, not critical for release

- [x] **PRIO1** _Chain needs to be changed automatically (Optimism)_
When I select Optimism for the dm3 name, write a name, and press "Claim", I get the error message "Invalid chain..." (see pic 01)
**EXPECTED:**  The app must automatically switch to the correct chain (in this case Optimism) (e.g., trigger a change in Metamask...)

- [x] **PRIO1** _Chain needs to be changed automatically (Gnosis)_
When I write my GNO name to publish the profile, I get the error "invalid chain..." (see pic 02)
**EXPECTED:** The app must automatically switch to the correct chain (in this case Gnosis) (e.g., trigger a change in Metamask...)

- [x] **PRIO1** _Title wrong_
When I change to "Gnosis GNO", it still says "ENS Name"
**EXPECTED:** It must change to "GNO Name"

- [x] **PRIO2** _Long time, full app overlay in config notifications_
When I switch to notifications, there comes an overlay over the whole app saying "Fetching notification channels", it takes about 3 seconds, the full component overlay comes at other actions, too.
**EXPECTED:** The fetching information (if needed) must be overlayed only on the notification page in the property dialog, do we really need to fetch something every time I visit this tab? The same is true for other overlays called from inside the notification configuration page.

- [x] **PRIO2** _Email notification setup - copy and paste_
When I receive the email with the OTP, I copy the number, go to the dm3 config, and paste it. Only the first digit is pasted. (see pic 03)
**EXPECTED:** All numbers are added correctly.

- [x] **PRIO1** _Email address of the notification_
I receive an email from "decentralized.essaging@gmail.com"
**REQ:** Change it to "notification@dm3.network" -> what needs to be prepared for this?

- [x] **PRIO1** _Email text_
How to edit the email template text (OTP message, notification message?
**OTP Email template** : https://github.com/dm3-org/dm3/blob/develop/packages/lib/delivery/src/notifications/templates/otp.ts
**New message Email template** : https://github.com/dm3-org/dm3/blob/develop/packages/lib/delivery/src/notifications/templates/newMessage.ts

- [x] **PRIO2** _Email registration lost, if deactivated_
When I deactivate email as a notification, it is correctly deactivated. When I return to the notification config page, the email address is removed and I have to register it.
**EXPECTED:** The registration is still there and can be reactivated by setting the checkmark (without the registration process). (It works, if I deactivate notifications completely and later reactivate it.)

## Pictures
01
<img width="1051" alt="image" src="https://github.com/dm3-org/dm3/assets/26625404/539c26c2-ffe3-4f75-948d-5003f93cb1d6">

02
<img width="1019" alt="image" src="https://github.com/dm3-org/dm3/assets/26625404/73337f5a-bff6-4abf-9c26-21b142eaf8e3">

03
![image](https://github.com/dm3-org/dm3/assets/26625404/8e2f8971-8336-47fb-86ba-04336dca3405)

**Comment by Bhupesh-mfsi** [comment]
**To setup email** notification@dm3.network

1. **Choose an Email Hosting Provider**: Look for email hosting providers that offer services suitable for your company's needs. Popular options include Google Workspace (formerly G Suite), Microsoft 365, Zoho Mail, and Rackspace Email.
2. **Select a Plan**: Review the plans offered by your chosen email hosting provider and select one that fits your requirements in terms of storage, number of email accounts, features, and pricing.
3. **Register Your Domain**: If you haven't already registered your company domain, you'll need to do so. Domain registration services are offered by various companies known as domain registrars. Some popular registrars include GoDaddy, Namecheap, and Google Domains.
4. **Set up DNS Records**: Once you've registered your domain, you'll need to set up the necessary DNS (Domain Name System) records to point to your email hosting provider. This typically involves adding MX (Mail Exchange) records to your domain's DNS settings. Your email hosting provider will provide you with the specific MX records to add.
5. **Create Email Accounts**: After setting up your DNS records, you can usually create email accounts using your email hosting provider's administration panel. You'll need to choose the usernames and passwords for each email account you create.

After this setup we need **HOST**, **PORT No**, **EMAIL ID**, **USERNAME** & **PASSWORD** to be used in backend
