### ISSUE TITLE
UI-Tests (02-05)

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#927]
### TESTED VERSION: STAGING 2024-05-08T10:20:55 a0ddf4

> **PRIO1** ... critical bug, blocks release
> **PRIO2** ... bug, but doesn't block release
> **PRIO3** ... not nice, not critical for release

- [x] **PRIO1** _Network switch at wrong action for dm3 name_
The network change in the wallet is triggered when the user selects the method for the dm3 name storage (at the moment: cloud or op )
**EXPECTED:** The network change must be executed only if the "claim and publish" button is pressed.

- [x] **PRIO1** _Network switch at wrong action for ens/gno name_
the same as above
**EXPECTED:** The network change must be executed only if the "publish" button is pressed.

- [x] **PRIO1** _Network mismatch (related to errors above)_
When I switch to op at dm3 name and later to gno and then press "claim and publish" for the op-dm3 name, the wrong network is selected (gnosis). 
**EXPECTED:** In the moment of publishing, the correct network must be selected. ALWAYS: when I publish and need network XYZ, this network needs to be activated in this moment. (The error is valid, if the user declines a network change).

- [x] **PRIO2** _Copy and paste still not correct_
When I copy the OTP from the email and past it to the input mask, only the first number is pasted, and the cursor jumps to position 2
**EXPECTED:** All numbers are added (this is common praxis at other apps)

- [x] **PRIO1** _Add info text to notifications_
**ADD:** "Experimental function. Do not use in production!"
(Reason: we need to add some functions required for European regulation). see pic 01

- [x] **PRIO2** _No network selection at signin_
When I sign in, it can happen that dm3 asks for a network change. (e.g. if I selected something in the config dialog before a refresh.
**EXPECTED:** at the sign-in, we don't care what network the user is connected to! No network change requests at this point because the user will be confused of this!

### Pictures

01
![image](https://github.com/dm3-org/dm3/assets/26625404/56d7ef47-3968-47a0-9e1e-4ff3da7e64aa)

**Comment by Bhupesh-mfsi** [comment]
**Copy paste issue**
The reason is copy clipboard not works on HTTP. This is the same issue we encountered on copying address in Rainbowkit modal. It works on localhost & on https secure context, but not on insecure context http. For more details it check this https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
